### ISSUE TITLE
Start using an issue tracker

### ISSUE THREAD

**Issue by jaegerpicker** [HomesteadOS/HomesteadOS#3]
We need to publish a timeline and planned feature set for version 1.0. Maybe right in github issues? Seems the easiest. Probably need to update the readme/start some documentation also. Wiki? Probably good enough for now.

Any thoughts @jforest ?

**Comment by jaegerpicker** [comment]
I think I'm making a call here and just using the github issue tracker/project board.

**Comment by jforest** [comment]
Sorry for not getting to these in a timely manner!  I think github issues/project boards are just fine for our needs here.
